# Config strings
blockbuster.config:
    title: Blockbuster

    general:
        title: General
        tooltip: General config options of Blockbuster mod

        show_first_time_modal: Show first time modal
        extra_wubs: Extra Wubs
        auto_refresh_models: Refresh models and skins
        debug_playback_ticks: Debug ticks
        green_screen_sky: Chroma sky
        green_screen_sky_color: Chroma sky color
        url_skins_sync_download: Synchronous URL downloads
        add_utility_blocks: Add utility blocks
        cached_structure_rendering: Cached structure rendering
    
    model_block:
        title: Model block
        tooltip: Model block related config options
        
        model_block_disable_rendering: Disable model block rendering
        model_block_disable_item_rendering: Disable item rendering
        restore: Restore model blocks
        reset_on_playback: Reset on playback
    
    recording:
        title: Recording
        tooltip: Here is everything related to player recording system

        recording_countdown: Recording countdown
        recording_delay: Recording frame skip
        record_unload_time: Automatic record unload time
        record_unload: Automatic record unloading
        record_sync_rate: Record tick sync rate
        record_attack_on_swipe: Attack on swipe
        record_commands: Record commands
        record_chat_prefix: Chat action prefix
        record_pause_preview: Better preview
    
    actor:
        title: Actor
        tooltip: Actor entity configuration option (not related to fake player)

        actor_fall_damage: Actor fall damage
        actor_tracking_range: Actor tracking range
        actor_rendering_range: Actor rendering range
        actor_always_render: Always render actor
        actor_always_render_names: Always render actor names
        actor_swish_swipe: Swipe swish
        actor_y: Fix Y motion
        actor_disable_riding: Disable riding
        actor_playback_body_yaw: Playback body yaw

    damage_control:
        title: Damage control
        tooltip: Damage control is a system which puts back blocks after an actor got recorded or scene finished playback
        
        damage_control: Damage control
        damage_control_distance: Damage distance

    model_folders:
        title: Model Folders
        tooltip: Add additional model folders

        path: Additional Folder

    snowstorm:
        title: Snowstorm
        tooltip: Snowstorm is a particle system that allows create pretty sophisticated particles, here you can find global options related to its particle system

        depth_sorting: Particle depth sorting

    audio:
        title: Audio
        tooltip: Options for in-game audio sync feature

        waveform_visible: Audio bars visible
        waveform_density: Waveform density
        waveform_width: Audio bar width
        waveform_height: Audio bar height
        waveform_filename: Show audio bar's filename