# Config strings
blockbuster.config:
    general:
        title: General
        
        load_models_on_login: Send models
        clean_model_downloads: Clean model downloads
        disable_teleport_playback_button: Disable playback button teleport
        extra_wubs: Extra Wubs
        auto_refresh_models: Refresh models and skins
    
    recording:
        title: Recording

        recording_countdown: Recording countdown
        recording_delay: Recording frame skip
        record_unload_time: Automatic record unload time
        record_unload: Automatic record unloading
        record_sync_rate: Record tick synchronization rate
        record_attack_on_swipe: Attack on swipe
        record_commands: Record commands
    
    actor:
        title: Actor
        
        actor_fall_damage: Actor fall damage
        actor_tracking_range: Actor tracking range
        actor_rendering_range: Actor rendering range
        actor_always_render_names: Always render actor names

    damage_control:
        title: Damage control
        
        damage_control: Damage control
        damage_control_distance: Damage distance