blockbuster.config.comments:
    general:
        show_first_time_modal: Whether first time modal should be shown in the dashboard
        extra_wubs: This option does literally nothing. Or maybe it does...?
        auto_refresh_models: Refresh models and skins when entering in Metamorph or Blockbuster GUIs?
        debug_playback_ticks: Write ticks in the log during scene playback
        green_screen_sky: Makes the sky solid color for chroma keying purposes
        green_screen_sky_color: Specifies the sky color for chroma sky feature
        url_skins_sync_download: Synchronous downloading of URL skins. It makes it work URL skins with 3D outer layers at cost of freezing the game to download a skin
        add_utility_blocks: Add blocks such as command and structure blocks to Blockbuster's creative tab to simplify access to these items
        cached_structure_rendering: If enabled, structure morph will be using more performant way of rendering structures, however, some mods' blocks, like Chisel&Bits', will be invisible
        bb_gun_sync_distance: If it's greater than 0, this option enables BB gun projectile synchronization, which makes projectile sync with the server, but at the cost of jittery teleportation

    model_block:
        model_block_disable_rendering: Whether model blocks should be rendered
        model_block_disable_item_rendering: Whether model block item rendering should be disabled (who would want that?)
        restore: This option allows to bring back old bug that allows to restore broken by accident model blocks.
        reset_on_playback: When enabled, once a scene starts playing all playback, all model blocks will reset themselves

    recording:
        recording_countdown: Recording countdown (in seconds)
        record_unload_time: How long does it take to unload a record (in ticks)
        record_unload: Enable automatic record unloading?
        record_sync_rate: How often a recording is going to synchronize with the server?
        record_attack_on_swipe: Does attack action get recorded with swipe action?
        record_commands: Does command action get recorded during recording?
        record_chat_prefix: Prefix which will get prepended to the actual message in the chat action (%%NAME%% wild card supported for current actor's name)
        record_pause_preview: This option enabled preview of animated morphs like image morph animations, animated poses, record morphs and sequencers. It's affects performance of the server side.

    actor:
        actor_fall_damage: Do actors receive fall damage?
        actor_tracking_range: How far actors are tracked? Requires restart of the game.
        actor_rendering_range: How far actors are seen?
        actor_always_render: Make actor always rendered, no matter where it is or its hitbox size
        actor_always_render_names: Enable unconditional actor nametag rendering
        actor_swish_swipe: Do actors emit swish sound when swiping?
        actor_y: Makes actors use correct Y value (fixes issue with hovering and jumping, but makes Y movement sharp)
        actor_disable_riding: Disable an option to being able to ride the actor by right clicking it
        actor_playback_body_yaw: Whether separate recorded horizontal body rotation should be played back on the actor (this guarantees consistent body rotation how it was recorded, it works only on new recordings recorded on Blockbuster 2.1+)

    damage_control:
        damage_control: Whether damage control is enabled
        damage_control_distance: Radius of effect for damage control

    model_folders:
        path: Absolute path to additional model Folder (on windows add the drive letter)

    snowstorm:
        depth_sorting: When enabled is fixes the particles being seen behind other semi-transparent particles. This option is very performance intensive, consider it using only when rendering video footage

    audio:
        waveform_visible: Whether audio bars should be shown when they're playing back
        waveform_density: How many pixels of audio waveform should be shown per second
        waveform_width: Width of an audio bar in floating point percentage (between 0 and 1)
        waveform_height: Height of an audio bar in pixels
        waveform_filename: Whether filename of the played audio in the audio should be shown