blockbuster.config.comments:
    general:
        disable_teleport_playback_button: Is teleport feature disabled when you sneak and using the playback button?
        extra_wubs: This option does literally nothing. Or maybe it does...?
        auto_refresh_models: Refresh models and skins when entering in Metamorph or Blockbuster GUIs?
        debug_playback_ticks: Write ticks in the log during director block recording
        green_screen_sky: Makes the sky fully green for chroma keying purposes
        url_skins_sync_download: Synchronous downloading of URL skins. It makes it work URL skins with 3D outer layers at cost of freezing the game to download a skin

    model_block:
        model_block_disable_rendering: Whether model blocks should be rendered
        model_block_disable_item_rendering: Whether model block item rendering should be disabled (who would want that?)

    recording:
        recording_countdown: Recording countdown (in seconds)
        recording_delay: Frame delay for recording
        record_unload_time: How long does it take to unload a record (in ticks)
        record_unload: Enable automatic record unloading?
        record_sync_rate: How often a recording is going to synchronize with the server?
        record_attack_on_swipe: Does attack action get recorded with swipe action?
        record_commands: Does command action get recorded during recording?
        record_chat_prefix: Prefix which will get prepended to the actual message in the chat action (%NAME% wild card supported for current actor's name)

    actor:
        actor_fall_damage: Do actors receive fall damage?
        actor_tracking_range: How far actors are tracked? Requires restart of the game.
        actor_rendering_range: How far actors are seen?
        actor_always_render: Make actor always rendered, no matter where it is or its hitbox size
        actor_always_render_names: Enable unconditional actor nametag rendering
        actor_swish_swipe: Do actors emit swish sound when swiping?
        actor_y: Makes actors use correct Y value (fixes issue with hovering and jumping, but makes Y movement sharp)

    damage_control:
        damage_control: Whether damage control is enabled
        damage_control_distance: Radius of effect for damage control
