blockbuster.config.comments:
    general:
        disable_teleport_playback_button: 当你蹲着使用播放按钮的时候，传送功能是否开启？
        extra_wubs: 这个选项可能没有作用，或者有点用？
        auto_refresh_models: 当进入 Metamorph 或 Blockbuster 的 GUI 时，自动刷新模型和皮肤？
        debug_playback_ticks: 当导演方块录制时，将 tick 时间写入日志文件
        green_screen_sky: 将天空完全变绿，用来键控抠像
        url_skins_sync_download: 同步的下载来自 URL 的皮肤。它可能会在下载 3D 外表层的时候导致游戏假死。

    model_block:
        model_block_disable_rendering: 是否要渲染模型方块
        model_block_disable_item_rendering: 是否要关闭模型方块的物品渲染（有人想要关掉吗？）
        
    recording:
        recording_countdown: 录制倒计时（秒）
        recording_delay: 录制的帧延迟
        record_unload_time: 卸载一个录制需要多久？（tick）
        record_unload: 开启自动卸载录制？
        record_sync_rate: 与服务器同步一个回放的频率是？
        record_attack_on_swipe: 是否录制挥手时，生物受到的伤害？
        record_commands: 是否录制玩家输入的命令？
        record_chat_prefix: 将会在确切要执行的命令之前预先用的前缀（%NAME% 通配符可用于指向演员的名称）

    actor:
        actor_fall_damage: 演员是否会掉落伤害？
        actor_tracking_range: 演员跟踪会多远？需要重启游戏。
        actor_rendering_range: 演员多远可见？
        actor_always_render: 让演员始终渲染，不管演员在哪里、碰撞箱有多大
        actor_always_render_names: 开启无条件渲染演员名称
        actor_swish_swipe: 当演员挥手时是否产生刷刷声？
        actor_y: 让演员使用正确的 Y 坐标值（可修复飞行时和跳跃时的问题，但会导致 Y 轴上的运动不平滑）

    damage_control:
        damage_control: 伤害控制是否开启
        damage_control_distance: 伤害控制效果的半径范围
