# Config strings
blockbuster.config:
    general:
        title: 通用

        disable_teleport_playback_button: 关闭播放后瞬移功能
        extra_wubs: 附加的杂物
        auto_refresh_models: 刷新模型和皮肤
        debug_playback_ticks: Debug ticks
        green_screen_sky: 绿色的天空
        url_skins_sync_download: 同步的 URL 下载
        
    model_block:
        title: 模型方块
        
        model_block_disable_rendering: 关闭模型方块渲染
        model_block_disable_item_rendering: 关闭物品栏渲染

    recording:
        title: 录制

        recording_countdown: 录制倒计时
        recording_delay: 录制跳过帧
        record_unload_time: 自动卸载录制的时间
        record_unload: 自动卸载录制的
        record_sync_rate: 录制 tick 的同步率
        record_attack_on_swipe: 挥动手攻击
        record_commands: 录制命令
        record_chat_prefix: 聊天动作的前缀
        
    actor:
        title: 演员

        actor_fall_damage: 演员掉落伤害
        actor_tracking_range: 演员跟踪范围
        actor_rendering_range: 演员渲染范围
        actor_always_render: 总是渲染演员
        actor_always_render_names: 总是渲染演员的名称
        actor_swish_swipe: 手臂划动刷刷声
        actor_y: 修复 Y 轴运动

    damage_control:
        title: 伤害控制

        damage_control: 伤害控制
        damage_control_distance: 伤害距离
