# Config strings
blockbuster.config:
    title: Blockbuster

    general:
        title: 常规
        tooltip: Blockbuster mod 的常规选项

        show_first_time_modal: 展示首次使用提示
        extra_wubs: 附加的杂物
        auto_refresh_models: 刷新模型和皮肤
        debug_playback_ticks: 调试 Ticks
        green_screen_sky: 色度天空
        green_screen_sky_color: 色度天空颜色
        url_skins_sync_download: 同步的 URL 下载
        add_utility_blocks: 添加实用方块
        bb_gun_sync_distance: BB 枪距离同步

    model_block:
        title: 模型方块
        tooltip: 与模型方块相关的选项

        model_block_disable_rendering: 禁用模型方块渲染
        model_block_disable_item_rendering: 禁用物品栏渲染
        model_block_missing_name_rendering: 渲染丢失模型的路径
        model_block_debug_rendering_f1: 在 F1 模式下渲染模型方块调试效果
        restore: 恢复模型方块
        reset_on_playback: 回放时重置

    recording:
        title: 录制与回放
        tooltip: 所有与玩家回放系统相关的选项

        recording_countdown: 录制倒计时
        record_unload_time: 自动卸载录制的时间
        record_unload: 自动卸载录制
        record_sync_rate: 录制 Tick 的同步率
        record_attack_on_swipe: 挥手攻击
        record_commands: 录制命令
        record_chat_prefix: 聊天动作前缀
        record_pause_preview: 预览增强

    scenes:
        title: 场景
        tooltip: 所有与场景相关的选项

        save_update: 保存后更新场景

    actor:
        title: 演员
        tooltip: 演员实体配置选项（与假玩家无关）

        actor_fall_damage: 演员跌落伤害
        actor_tracking_range: 演员跟踪范围
        actor_rendering_range: 演员渲染范围
        actor_always_render: 始终渲染演员
        actor_always_render_names: 始终渲染演员的名称
        actor_swish_swipe: 手臂划动刷刷声
        actor_y: 修复 Y 轴运动
        actor_disable_riding: 禁用骑乘
        actor_playback_body_yaw: 回放身体偏航

    damage_control:
        title: 破坏控制
        tooltip: 破坏控制是指在演员被录制或场景完成回放后，恢复方块的系统

        damage_control: 破坏控制
        damage_control_distance: 破坏距离
        damage_control_message: 破坏控制提示

    model_folders:
        title: 模型文件夹
        tooltip: 添加附加的模型文件夹

        path: 附加文件夹

    snowstorm:
        title: Snowstorm
        tooltip: Snowstorm 是一个可以创建相当复杂的粒子的例子系统，在这里你可以找到与该粒子系统相关的全局选项

        depth_sorting: 粒子按深度排序

    audio:
        title: 音频
        tooltip: 游戏内音频同步功能相关的选项

        waveform_visible: 音频条可见
        waveform_density: 波形密度
        waveform_width: 音频条宽度
        waveform_height: 音频条高度
        waveform_filename: 显示音频条的文件名
        waveform_time: 显示音频条的播放时间
        audio_sync: 在服务器与客户端之间同步音频

    onion_skin:
        title: 洋葱皮

        seq_prev: 先前的伪装
        seq_prev_color: 先前的伪装颜色
        seq_next: 后续的伪装
        seq_next_color: 后续的伪装颜色
        seq_loop_color: 循环位移标记

    immersive_editor:
        title: 沉浸式编辑器
        tooltip: 沉浸式编辑器开关

        model_block: 模型方块
        record_editor: 回放编辑器
