# Config strings
blockbuster.config:
    title: Блокбастер

    general:
        title: Общие
        tooltip: Общие параметры конфигурации Блокбастера
        
        show_first_time_modal: Показывать заставку первого запуска
        extra_wubs: Экстра тыцы
        auto_refresh_models: Автоматическое обновление скинов и моделей
        debug_playback_ticks: Тики отладки
        green_screen_sky: Хроманебо
        green_screen_sky_color: Цвет хроманеба
        url_skins_sync_download: Синхронная загрузка ссылок
        add_utility_blocks: Добавить полезные блоки
        cached_structure_rendering: Кэшированное отображение структур
        bb_gun_sync_distance: Дистанция синхронизации ББ Оружия
    
    model_block:
        title: Блоки-модели
        tooltip: Параметры конфигурации, относящиеся к блокам-моделям
        
        model_block_disable_rendering: Выключить отображение блоков-моделей
        model_block_disable_item_rendering: Выключить отображение предметов
        restore: Восстановление блоков-моделей
        reset_on_playback: Сбросить по взаимодействию
    
    recording:
        title: Процесс Записи
        tooltip: Параметры конфигурации, относящиеся к системе записи игрока

        recording_countdown: Отсчёт до начала записи
        record_unload_time: Автоматическая регулировка времени выгрузки записей
        record_unload: Автоматическая выгрузка записей
        record_sync_rate: Индикатор синхронизации тиков
        record_attack_on_swipe: Атака взмахом
        record_commands: Запись команд
        record_chat_prefix: Префикс действия в чате
        record_pause_preview: Улучшенный предпросмотр

    scenes:
        title: Сцены
        tooltip: Здесь находится всё ,что относится ко сценам

        save_update: Обновить после сохранения
    
    actor:
        title: Актёры
        tooltip: Параметры конфигурации существ категории актёр (не применяются к поддельному игроку)
        
        actor_fall_damage: Урон от падения для актёров
        actor_tracking_range: Диапазон отслеживания актёров
        actor_rendering_range: Диапазон отображения актёров
        actor_always_render: Всегда отображать актёров
        actor_always_render_names: Всегда отображать имена актёров
        actor_swish_swipe: Вжух при взмахе
        actor_y: Исправить движение по оси Y
        actor_disable_riding: Отключить катание верхом на морфах
        actor_playback_body_yaw: Рыскание тела воспроизведения

    damage_control:
        title: Контроль урона
        tooltip: Контроль урона это система, которая возвращает на место поставленные или уничтоженные актёром блоки по завершению процесса записи или воспроизведения записи
        
        damage_control: Контроль урона
        damage_control_distance: Дистанция урона

    model_folders:
        title: Папки Моделей
        tooltip: Добавить дополнительные папки моделей

        path: Дополнительная папка

    snowstorm:
        title: Snowstorm
        tooltip: Snowstorm - это система частиц, которая позволяет создавать довольно сложные частицы, здесь вы можете найти глобальные настройки, связанные с системами частиц

        depth_sorting: Глубина фильтрации частиц

    audio:
        title: Аудио
        tooltip: Настройки для внутриигровой возможности синхронизировать аудио

        waveform_visible: Видимость аудиополос
        waveform_density: Плотность аудиополосы
        waveform_width: Ширина аудиополосы
        waveform_height: Высота аудиополосы
        waveform_filename: Показывать название файла аудиополосы
